# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
ZSH=/home/f/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
ZSH_THEME="grimme"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git history-substring-search)


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="~/.ssh/dsa_id"

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export JAVA_HOME=/usr/lib/jvm/java-24-openjdk
export PATH=/usr/local/go/bin:/usr/local/lib:$JAVA_HOME/bin:$GOBIN:$PATH
export PATH=/home/f/.local/bin:$PATH
export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export PATH=$HOME/work/bin:$PATH
export PATH=/usr/bin/i3:$PATH
export PATH=/usr/local:$PATH

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin

export CARGO_NET_GIT_FETCH_WITH_CLI=true

export XDG_CURRENT_DESKTOP=KDE

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# if [ -f /etc/bash_completion ]; then
#  . /etc/bash_completion
# fi

# if [ -f /usr/share/git/completion/git-completion.bash ]; then
#  . /usr/share/git/completion/git-completion.bash
# fi

export EDITOR=nvim

# unsetopt share_history
# setopt no_share_history

# zsh make vim work with <c-s>
# alias vim="stty stop '' -ixoff ; vim"

# `Frozing' tty, so after any command terminal settings will be restored
ttyctl -f

# pet
function prev() {
  PREV=$(fc -lrn | head -n 1)
  sh -c "pet new `printf %q "$PREV"`"
}
function pet-select() {
  BUFFER=$(pet search --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N pet-select
stty -ixon
bindkey '^s' pet-select

# load xresources
# [[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

# disable beep
setopt NO_BEEP
xset b off

export CLOUDSDK_PYTHON=/usr/bin/python
export TK_IM_MODULE=fcitx
export T_IM_MODULE=fcitx
export MODIFIERS=@im=fcitx

# zh service account key
export GOOGLE_APPLICATION_CREDENTIALS=~/.config/gcloud/credentials/zhong-366420-2deae11a74e0.json

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform
source ~/.zcredentials

[ -f "/home/f/.ghcup/env" ] && source "/home/f/.ghcup/env" # ghcup-env
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/f/work/src/github.com/fbngrm/zh-anki/google-cloud-sdk/path.zsh.inc' ]; then . '/home/f/work/src/github.com/fbngrm/zh-anki/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/f/work/src/github.com/fbngrm/zh-anki/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/f/work/src/github.com/fbngrm/zh-anki/google-cloud-sdk/completion.zsh.inc'; fi
[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

if [ -f '/home/f/keys' ]; then source '/home/f/keys'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"
